### PR TITLE
Removed some files generated by operating systems

### PR DESCRIPTION
**Pull request by ottopasuuna**
There might be some more that I missed.

### CODE REVIEW

**Comment by ausshir** [comment]
Who has authority to close pull requests?

**Comment by ottopasuuna** [comment]
It looks like I can. Do we want to create merge commits, or "Squash and merge"? Merge commits might create a lot of noise, but retain information of the flow of branches.

**Comment by ausshir** [comment]
What close method did you choose?

**Comment by ottopasuuna** [comment]
Squash and merge.

**Pull request merged**
